name: mfg_dashboard
description: Manufacturing Dashboard
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^31.1.17
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^16.2.1
  flutter_hooks: ^0.21.3+1
  envied: ^0.5.4+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1
  riverpod_generator: ^2.4.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
