name: mfg_dashboard
description: Manufacturing Dashboard
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^30.2.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^13.2.1
  flutter_hooks: ^0.20.5
  envied: ^0.5.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.3
  riverpod_generator: ^2.3.5
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
